/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LogProject;

import java.util.Properties;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;

public class App {

    public static final String ANSI_RESET = "\u001B[0m";
    public static final String ANSI_BLACK = "\u001B[30m";
    public static final String ANSI_RED = "\u001B[31m";
    public static final String ANSI_GREEN = "\u001B[32m";
    public static final String ANSI_YELLOW = "\u001B[33m";
    public static final String ANSI_BLUE = "\u001B[34m";
    public static final String ANSI_PURPLE = "\u001B[35m";
    public static final String ANSI_CYAN = "\u001B[36m";
    public static final String ANSI_WHITE = "\u001B[37m";

    static Logger logger = LogManager.getLogger(App.class.getName());

    public static void main(String[] args) {
        Configurator.setRootLevel(Level.ALL);

        App app = new App();
        if (app.setLevel(args[0])) {
            app.run();
        }
    }

    private boolean setLevel(String level) {
        if (level.equals("TRACE"))
            Configurator.setLevel(App.class, Level.TRACE);
        else if (level.equals("DEBUG"))
            Configurator.setLevel(App.class, Level.DEBUG);
        else if (level.equals("INFO"))
            Configurator.setLevel(App.class, Level.INFO);
        else if (level.equals("WARN"))
            Configurator.setLevel(App.class, Level.WARN);
        else if (level.equals("ERROR"))
            Configurator.setLevel(App.class, Level.ERROR);
        else if (level.equals("FATAL"))
            Configurator.setLevel(App.class, Level.FATAL);
        else if (level.equals("OFF"))
            Configurator.setLevel(App.class, Level.OFF);
        else
            return false;
        return true;
    }

    public void run() {
        logger.trace(ANSI_GREEN + "> This is a TRACE message" + ANSI_RESET);
        logger.debug(ANSI_PURPLE + "> This is a DEBUG message" + ANSI_RESET);
        logger.info(ANSI_BLUE + "> This is an INFO message" + ANSI_RESET);
        logger.warn(ANSI_YELLOW + "> This is a WARN message" + ANSI_RESET);
        logger.error(ANSI_RED + "> This is an ERROR message" + ANSI_RESET);
        logger.fatal(ANSI_RED + "> This is a FATAL message" + ANSI_RESET);
        // if logger level is off
        if (logger.getLevel() == Level.OFF)
            System.out.println(ANSI_CYAN + "> This is an OFF message" + ANSI_RESET);
    }
}
